services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_URL=https://blueskyafrika.cc
      - MONGODB_URI=mongodb://mongodb:27017/pos
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: always
    depends_on:
      - mongodb

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: https://blueskyafrika.cc
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    restart: always
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
