services:
  - type: web
    name: bluesky-frontend
    env: docker
    region: frankfurt
    plan: starter
    branch: main
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_BACKEND_URL
        value: https://bluesky-backend.onrender.com
    healthCheckPath: /
    numInstances: 1

  - type: web
    name: bluesky-backend
    env: docker
    region: frankfurt
    plan: starter
    branch: main
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: FRONTEND_URL
        value: https://bluesky-frontend.onrender.com
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
    healthCheckPath: /api/health
    numInstances: 1
